image: nixos/unstable
sources:
  - https://git.sr.ht/~rycee/mozilla-addons-to-nix
secrets:
  - 01ad357c-3214-4f73-bb7e-2441e440cc51
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
packages:
  - nixos.cachix
tasks:
  - setup: |
      cachix use rycee
  - build: >-
      nix build -L ./mozilla-addons-to-nix
  - cache: |
      cachix push rycee result
